CREATE TABLE public.content_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    metadata JSONB
);


COMMENT ON TABLE public.content_documents IS 'Stores unstructured JSON data extracted by the AI from web content.';

  -- function for searching the nlp
  CREATE OR REPLACE FUNCTION execute_sql (query_string TEXT)
  RETURNS SETOF json AS $$
  BEGIN
    -- Basic validation: Only allow SELECT queries on the specific table
    IF lower(query_string) LIKE 'select%from public.content_documents%' THEN
      RETURN QUERY EXECUTE query_string;
    ELSE
      RAISE EXCEPTION 'Invalid or disallowed query type: %', query_string;
    END IF;
  END;
  $$ LANGUAGE plpgsql SECURITY DEFINER;

  -- Grant execute permission to the service_role
  GRANT EXECUTE ON FUNCTION execute_sql(text) TO service_role;