CREATE TABLE public.content_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    metadata JSONB
);


COMMENT ON TABLE public.content_documents IS 'Stores unstructured JSON data extracted by the AI from web content.';

  -- function for searching the nlp
  CREATE OR REPLACE FUNCTION execute_sql (query_string TEXT)
  RETURNS SETOF json AS $$
  BEGIN
    -- Basic validation: Only allow SELECT queries on the specific table
    IF lower(query_string) LIKE 'select%from public.content_documents%' THEN
      RETURN QUERY EXECUTE query_string;
    ELSE
      RAISE EXCEPTION 'Invalid or disallowed query type: %', query_string;
    END IF;
  END;
  $$ LANGUAGE plpgsql SECURITY DEFINER;

  -- Grant execute permission to the service_role
  GRANT EXECUTE ON FUNCTION execute_sql(text) TO service_role;

  CREATE TABLE IF NOT EXISTS public.mobile_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL,
    app_version TEXT,
    platform TEXT, -- 'ios' or 'android'
    last_active TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    push_token TEXT, -- For future push notifications
    settings JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE public.mobile_devices IS 'Tracks registered mobile devices for SnapMind app';

-- Index for quick device lookups
CREATE INDEX idx_mobile_devices_device_id ON public.mobile_devices(device_id);

-- Note: The main content_documents table doesn't need any changes!
-- Mobile-shared content uses the exact same schema as web extension content.