-- 1. DROP THE OLD TABLE AND FUNCTION if they exist
DROP FUNCTION IF EXISTS public.execute_sql(text);
DROP TABLE IF EXISTS public.content_documents;

-- 2. CREATE THE NEW content_documents TABLE
CREATE TABLE public.content_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- NEW: Link to the authenticated user
    -- Assumes you are using Supabase Auth, which uses UUIDs for users
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    
    -- NEW: Source tracking ('W' for Web, 'M' for Mobile)
    source CHAR(1) CHECK (source IN ('W', 'M')),
    
    metadata JSONB,
    
    -- Full-text search vector (assuming you still want this)
    -- You will need to create a trigger to update this column
    -- from 'metadata' fields like title, summary, keywords.
    fts TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple',
            jsonb_path_query_array(metadata, '$.keywords[*]') ||
            to_tsvector('simple', coalesce(metadata->>'title', '')) ||
            to_tsvector('simple', coalesce(metadata->>'summary', ''))
        )
    ) STORED
);

COMMENT ON TABLE public.content_documents IS 'Stores unstructured JSON data extracted by the AI, segregated by user.';

-- 3. CREATE INDEXES
-- Index for the user_id to make lookups fast
CREATE INDEX idx_content_documents_user_id ON public.content_documents(user_id);
-- Index for Full-Text Search
CREATE INDEX content_documents_fts_idx ON public.content_documents USING GIN (fts);
-- Index for JSONB metadata (emotions, keywords)
CREATE INDEX idx_content_documents_metadata_gin ON public.content_documents USING GIN (metadata);


-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- This is the most important step for multi-user security
ALTER TABLE public.content_documents ENABLE ROW LEVEL SECURITY;

-- 5. CREATE RLS POLICIES
-- Policy 1: Users can see *only* their own documents
CREATE POLICY "User can see only their own documents"
ON public.content_documents FOR SELECT
USING (auth.uid() = user_id);

-- Policy 2: Users can insert documents *only* for themselves
CREATE POLICY "User can insert only their own documents"
ON public.content_documents FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy 3: Users can update *only* their own documents
CREATE POLICY "User can update only their own documents"
ON public.content_documents FOR UPDATE
USING (auth.uid() = user_id);

-- Policy 4: Users can delete *only* their own documents
CREATE POLICY "User can delete only their own documents"
ON public.content_documents FOR DELETE
USING (auth.uid() = user_id);