CREATE TABLE public.content_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    metadata JSONB
);


COMMENT ON TABLE public.content_documents IS 'Stores unstructured JSON data extracted by the AI from web content.';