import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { useSupabase } from '../context/SupabaseContext';
import { useNavigation } from '@react-navigation/native';

const AddScreen = () => {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [tags, setTags] = useState('');
  const [loading, setLoading] = useState(false);
  const { supabase, session, getAuthToken } = useSupabase();
  const navigation = useNavigation();

  const handleSave = async () => {
    if (!title.trim() || !content.trim()) {
      Alert.alert('Error', 'Please add a title and content');
      return;
    }

    if (!session) {
      Alert.alert('Error', 'You must be logged in');
      return;
    }

    setLoading(true);
    
    try {
      // ✅ Create data matching your backend schema
      const memoryData = {
        user_id: session.user.id,
        metadata: {
          title: title.trim(),
          summary: content.trim(),
          keywords: tags ? tags.split(',').map(t => t.trim()).filter(t => t) : [],
          emotions: [], // Will be generated by backend
          favorite: false,
        },
        raw_text: content.trim(),
        source: 'M',
        created_at: new Date().toISOString(),
      };

      // ✅ Save directly to Supabase (bypass backend for now)
      const { error } = await supabase
        .from('content_documents')
        .insert([memoryData]);
      
      if (error) throw error;

      Alert.alert('Success', 'Memory saved!');
      
      // Clear form
      setTitle('');
      setContent('');
      setTags('');
      
      // Go back to Home and refresh
      navigation.navigate('Home');
    } catch (error) {
      console.error('Save error:', error);
      Alert.alert('Error', `Failed to save: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView 
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      style={styles.container}
    >
      <ScrollView>
        {/* ✅ HEADER */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Ionicons name="arrow-back-outline" size={24} color="#06b6d4" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Add Memory</Text>
          <View style={{ width: 24 }} />
        </View>

        <View style={styles.form}>
          <Text style={styles.label}>Title *</Text>
          <TextInput
            style={styles.input}
            placeholder="Give it a memorable title..."
            placeholderTextColor="#666"
            value={title}
            onChangeText={setTitle}
            maxLength={100}
          />

          <Text style={styles.label}>Content *</Text>
          <TextInput
            style={[styles.input, styles.textArea]}
            placeholder="Write your thoughts, notes, or paste content..."
            placeholderTextColor="#666"
            value={content}
            onChangeText={setContent}
            multiline
            textAlignVertical="top"
            numberOfLines={10}
          />

          <Text style={styles.label}>Tags (comma separated)</Text>
          <TextInput
            style={styles.input}
            placeholder="work, ideas, inspiration..."
            placeholderTextColor="#666"
            value={tags}
            onChangeText={setTags}
          />

          {loading ? (
            <ActivityIndicator size="large" color="#06b6d4" style={styles.loader} />
          ) : (
            <TouchableOpacity style={styles.button} onPress={handleSave}>
              <Text style={styles.buttonText}>Save Memory</Text>
            </TouchableOpacity>
          )}
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09090b',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#27272a',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fafafa',
  },
  form: {
    padding: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fafafa',
    marginBottom: 8,
    marginTop: 15,
  },
  input: {
    backgroundColor: '#18181b',
    color: '#fafafa',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  textArea: {
    height: 200,
    textAlignVertical: 'top',
  },
  loader: {
    marginTop: 30,
  },
  button: {
    backgroundColor: '#06b6d4',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 25,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default AddScreen;